services:
  db:
    image: postgres:latest
    container_name: bags-db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    container_name: "bags-app"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
volumes:
  db_data: