services:
  db:
    image: postgres:latest
    container_name: bags-db
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    container_name: "bags-app"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8080"
  fake:
    container_name: "fake-api"
    image: "ghcr.io/pablobaratta/fake-api:${FAKE_VERSION}"
    volumes:
      - ./testutil/balances.json:/app/balances.json
    environment:
     EXTERNAL_API_URL: "${API_URL}"
     EXTERNAL_API_TOKEN: "${EXTERNAL_API_TOKEN}"
    ports:
      - "${FAKE_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
  db_data: